### PR TITLE
easy_install throwing errors because pip switched from HTTP to HTTPS

### PR DESCRIPTION
**Pull request by dandinu**
Modified the shell script to use official install method for pip to avoid repo download errors.

### CODE REVIEW

**Comment by slicedevca** [comment]
This pull request has been lingering for a while, anyway we can get this merged?

**Comment by slicedevca** [comment]
@vovimayhem

**Comment by vovimayhem** [comment]
Oh my! I remember I passed the maintainer duties to someone else...

Let me see what I can do

**Comment by slicedevca** [comment]
Sweet! Thank you @vovimayhem

**Pull request merged**
