### PR TITLE
All Changes of PRs #3, #4 and #5

### PR DESCRIPTION
**Pull request by tknerr**
This "meta" PR adds all changes from these individual PRs:
- https://github.com/vovimayhem/vagrant-guest_ansible/pull/3 - unbuffered output
- https://github.com/vovimayhem/vagrant-guest_ansible/pull/4 - fix NoMethodError
- https://github.com/vovimayhem/vagrant-guest_ansible/pull/5 - add CentOS support

I also updated the version to `0.0.2.dev` so that it won't clash with the already released `0.0.1` version when I build and install it locally.

### CODE REVIEW

**Comment by bgazzera** [comment]
Thank you @tknerr, you just saved me a lot of typing, as I was already writing an issue because vagrant didn't install the latest version, and wasn't sure why. I was going to xref to this PR when I found your explanation.

+1 to bump the version to 0.0.2

Cheers

**Comment by warrenseine** [comment]
It doesn't work here:
* First, the plugin uses `File.basename` on the `inventory_path`, which makes it impossible to place it in a subdirectory.
* Second, it doesn't interpret `inventory_path` as a path (only as an inventory file, while it should use the `--limit` argument to find the correct inventory file if it exists.

Not patching because I hope the [`ansible_local`](https://github.com/mitchellh/vagrant/pull/5340) PR will remove the need of a plugin.

**Comment by tknerr** [comment]
@warrenseine I'm :+1: for having `ansible_local` properly done in vagrant core too

**Comment by gildegoma** [comment]
Hello Guys! 

Thank to @tknerr, I am quite recently aware of the existence of this plugin (so far I only knew about https://github.com/jaugustin/vagrant-ansible-local). 

One of the advantages of the upcoming buit-in provisioner is of course the ability to share lots of code parts with the `ansible` host-based provisioner. If you have time and will, it would be very helpful if some of you could check it out and let us know if your use cases will be well covered, or not...

To better organize the things, I proposed to use these two issues as following:

* https://github.com/mitchellh/vagrant/pull/2103: keep track of end-user feedbacks and request about this upcoming feature
* https://github.com/mitchellh/vagrant/pull/5340: comments should be ideally reserved to code review and bug fixing communication

Many thanks in advance for your help :)

**Comment by vovimayhem** [comment]
Dudes! As you may have noticed, I'm having trouble maintaining this project.

Anyone here interested in becoming the steward of this project?

**Pull request merged**
