### PR TITLE
Fixes vovimayhem/vagrant-guest_ansible#13 by adding missing dependencies

### PR DESCRIPTION
**Pull request by jehartzog**
Additional dependencies added are libffi-dev and libssl-dev. Adding these fixed the issue and was able to provision using ansible on a windows host.

### CODE REVIEW

**Comment by birish2** [comment]
Please merge this!

**Comment by firefly4268** [comment]
please merge!

**Comment by imikh** [comment]
Could you please merge this one.

**Comment by rbcarson** [comment]
I encountered this issue recently, but then discovered that this plugin isn't necessary anymore: [Vagrant 1.8.0](https://www.hashicorp.com/blog/vagrant-1-8.html) added the [`ansible_local` provisioner](https://www.vagrantup.com/docs/provisioning/ansible_local.html), which fulfills the same role.

**Comment by SSarang** [comment]
Not sure I can post this question here! 
I am using Vagrant Version 1.9.1 with windows 10 and getting below error
> drupalvm: Cannot find Ansible playbook.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Does anyone know about the solution?

**Pull request closed without merging**
